### ISSUE TITLE
pnpm build fails

### ISSUE THREAD

**Issue by delaneyj** [ctholho/vitespa#1]
**Describe the bug/issue**
[vite-plugin-pwa] [vite]: Rollup failed to resolve import "workbox-window" from "../../../../../../../../../@vite-plugin-pwa/virtual:pwa-register".

`pnpm i workbox-window` fixes it

**Comment by ctholho** [comment]
Thank you. I see there is an issue already at [vite-plugin-pwa](https://github.com/antfu/vite-plugin-pwa/issues/89). But I can not reproduce this.

Feel free to reopen if anything new comes up.
